apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: joker-<MY_NAME>
spec:
  minReplicas: 3
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: joker-<MY_NAME>
  targetCPUUtilizationPercentage: 60
