apiVersion: apps/v1
kind: Deployment
metadata:
  name: joker-<MY_NAME>
spec:
  replicas: 3
  selector:
    matchLabels:
      app: joker-<MY_NAME>
  template:
    metadata:
      labels:
        app: joker-<MY_NAME>
    spec:
      containers:
      - name: joker
        image: gcr.io/aramse-training/<MY_NAME>-joker-app:1.0
        resources:
          requests:
            cpu: 0.1
          limits:
            cpu: 0.1
        readinessProbe:
          httpGet:
            path: /health
            port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: joker-<MY_NAME>
spec:
  ports:
  - name: web
    port: 80
    targetPort: 80
  selector:
    app: joker-<MY_NAME>
  type: LoadBalancer
